# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vladyslav Alieiev
title: Specialist in Operation, Machinery and Equipment of Agribusiness
email: vladyslav.alieiev@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
facebook_username: lieiev
instagram_username: lieiev

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Solve unique tasks related to the <mark>maintenance</mark> and use of <mark>mechanized technologies</mark> of production, primary processing, storage and transportation of agricultural products. Expert management of mechanized technological processes and production units that provide technical support for an agro-industrial enterprise, with a proven record of elimination of failures.
  
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lariagra Farms  Ltd, AB, Canada
        link: https://www.sunterrafarms.ca/
        link_text: sunterrafarms.ca
        sub_title: Specialized livestock worker
        caption: August 2021 – Present 
        description: | # this will include new lines to allow paragraphs
           * Provide agricultural livestock services such as artificial insemination, assisting pregnant sows and sorting new-borns
           * Recognize and treat certain livestock health problems
           * Maintain livestock performance records
           * Work closely with all staff to meet monthly farrowing and mortality targets
           * Vaccinate animals according to farm protocols
      - layout: left
        title: Coles Farms Inc, NC, USA
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Farrowing/Breeding Technician
        caption: November 2019 – November 2020
        description: | # this will include new lines to allow paragraphs
           * Farrowing: assisted pregnant sows; weaned and sorted by sex piglets; sorted new-borns; pressure washing
           * Breeding: bred sows and gilts - both artificial insemination and natural
           * Vaccinated animals according to barn health protocol, fed and treated sick animals
           * Barn maintenance and routine repair, record keeping
           * Performed and executed the setting up, operation, and repair of farm machineries and equipment (Kubota tractor)
      - layout: left
        title: Westpork Pty Ltd, WA, Australia
        link: http://westpork.com.au/
        link_text: westpork.com.au
        sub_title: Machine Operator
        caption: September 2018 - October 2019
        description: | # this will include new lines to allow paragraphs
           + Cleaned pigsties and operated the farm equipment such as tractor Arion 620c, skid steer loader 226B, telehandler MLT-X732 and MLT-526 
           + Maintained the equipment by fuelling daily, greasing, and checking hydraulic fluid levels 
           + Drove a forklift to unload hay from the transport trucks and delivered to the pig shelter
           + Delivered piglets from one barn to another by using 3-ton truck
           + Prepared shelter for pigs by liming and scattering hay around the shed
      - layout: left
        title: Centrum Valley Farms, IA, USA
        link: http://www.centrumvalleyfarms.com/
        link_text: centrumvalleyfarms.com
        sub_title: Barn Worker/Mechanic
        caption: March 2016 – March 2017
        description: | # this will include new lines to allow paragraphs
          * Administered medications
          * Observed animals physical conditions to detect illness
          * Inspected motors, belts and ventilation system
          * Operated and maintained machines, inspected the final product
      - layout: left
        title: Valleyfair, MN, USA
        link: https://www.valleyfair.com/
        link_text: valleyfair.com
        sub_title: Ride Operator
        caption: June 2015  –September 2015
        description: | # this will include new lines to allow paragraphs
          * Check safety, control attractions, cleaning of the territory, communication and service by site visitors.
      - layout: left
        title: Farm Smaragd, Kalanchak, Ukraine
        # link: https://www.valleyfair.com/
        # link_text: valleyfair.com
        sub_title: Trainee
        caption:  05/05/14 to 01/11/14
        description: | # this will include new lines to allow paragraphs
          * Checking temperature & water in the barns. Feeding, general assisting during farrowing.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mykolayiv State Agrarian University
        link: https://www.mnau.edu.ua/
        link_text: mnau.edu.ua
        caption: 01/09/2012 – 30/06/2017
        sub_title: Bachelor’s Degree 
        quote: >
          Agroengineering on Power and Engineering Faculty
        description: | # this will include new lines to allow paragraphs
          During my time at university I learnt most of my key skills that have I have taken through my <mark>career</mark> such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy <mark>work</mark> life balance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Driving license: passenger car; trucks up to 16,500 pounds 
      - I have 6 years of the car driving experience;
      - 450 hours of driving Manitou & Bobcat (cleaning sheds); 
      - 300 hours of driving tractor Arion 620c / Kubota M9540 & 3 ton truck (transporting piglets & hogs).

      Alongside my interests in swine production some of my other interests and hobbies are:
      - kickboxing (trained after the lectures in the university for 4 years);
      - chess (played for 7 years in the school, currently playing rarely);
      - reading general education literature;
      - doing sports with own weight + jogging.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
